name: Build
on: [push]
jobs:
  it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ArtemGrubin/Buildozer-action@v1
        with:
          command: buildozer -v android debug
      - uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: bin/*.apk
